### ISSUE TITLE
Ensure contact-reading permissions disabled

### ISSUE THREAD

**Issue by patcon** [amoghbl1/Orfox#6]
Heyo! Maybe this is done already, but just a quick heads up.

Ref: https://github.com/mission-impossible-android/mission-impossible-android/issues/79#issuecomment-112917307

cc: @SchnWalter (it was orfox that you took that screenshot from right, albeit the old old orfox build?)

**Comment by SchnWalter** [comment]
I don't remember exactly, but it probably was the FDroid build of Firefox: https://f-droid.org/repository/browse/?fdfilter=fennec&fdid=org.mozilla.fennec_fdroid

**Comment by amoghbl1** [comment]
@SchnWalter Try out the new apks... Many updates have been made to it recently.
When it comes to the contacts, I've just removed the read/write permissions, working on the java code to completely disable it might take a little more time, so it will probably crash if you click allow there.
@patcon Thanks for pointing this out! I'm trying to make a comprehensive list of permissions to remove, those will make it in by the time of a beta release, I'd love some advice from you.
