### ISSUE TITLE
Is this the main OrFox repo?

### ISSUE THREAD

**Issue by herbsmn** [amoghbl1/Orfox#7]
With more press starting to come out about Orfox, I suggest that you edit your README to explain whether this is the main Orfox repo or not and if not, to link to the main repo so people can properly submit issues and stuff. If https://github.com/guardianproject/orfoxfennec is the main repo, why then hasn't anything been done there for 11 months?

**Comment by amoghbl1** [comment]
@herbsmn the official repo is https://github.com/guardianproject/OrfoxFennec
We use https://dev.guardianproject.info/projects/orfox-private-browser to track the project though, not github issues.
Current alpha builds are coming from my repo, but by the time we have a beta, we will update the guardianproject repo.

**Comment by subtuppel** [comment]
https://dev.guardianproject.info/projects/orfox-private-browser/orfox-private-browser/issues

returns "not found"

I was about to search issues for the "cannot add any addons to orfox-issue", by the way.

**Comment by leafcutterant** [comment]
Same here. @amoghbl1, the Guardian Project Redmine is not working. I tried to register but it returns "not found".
